input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [@timestamp] == nil {
    mutate {
      add_field => { "[@timestamp]" => "%{+YYYY-MM-dd'T'HH:mm:ss.SSSZ}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "monitoring-observability-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}

